### PR TITLE
Object notation in join-room-stateless

### LINKED ISSUE #174: Figure `join-room-stateless` adjustments
Notes from Darian:

```
Use object notation:

:LoadBalancer
1:Monolith
2:Monolith

and you can potentially underscore them, too.
```

Try not to make the diagram any wider because the text size will get smaller

### PR DESCRIPTION
**Pull request by cjrkoa**
Fixes #174

### CODE REVIEW

**Comment by cjrkoa** [comment]
Draft

**Comment by dyc3** [comment]
I thought I reassigned this to @Victor-M-Giraldo ?

**Comment by cjrkoa** [comment]
> I thought I reassigned this task to @Victor-M-Giraldo ?

We talked about it yesterday In the group message

**Comment by dyc3** [comment]
We'll clear this up at sprint planning

**Comment by dyc3** [comment]
Closing this to let @Victor-M-Giraldo do this as an onboarding task.

**Pull request closed without merging**
