### PR TITLE
add custom diagram to expo poster

### LINKED ISSUE #346: create load balancer visual for expo poster
As discussed in person:

Image

### PR DESCRIPTION
**Pull request by dyc3**
Would like to get feedback from everybody before merging

closes #346 

~how it currently looks~ outdated, see below:

image

### CODE REVIEW

**Review by cjrkoa — COMMENTED** [review]
This is one of those things that might be better to do in photoshop rather than programmatically

**Comment by dyc3** [comment]
I elected to do it like this so that there's no chance that the graphic gets pixelated when we submit it to get printed, and so it's diffable in version control.

**Comment by cjrkoa** [comment]
> I elected to do it like this so that there's no chance that the graphic gets pixelated when we submit it to get printed, and so it's diffable in version control.

we can talk about more tomorrow

**Comment by Victor-M-Giraldo** [comment]
I don't really have a preference here for how we should make it, but if for some reason we chose to do it with Photoshop, you can export certain things as SVGs as well. Other than that I think this is fine.

**Comment by dyc3** [comment]
I've revised the diagram a little

image

**Review by cjrkoa — APPROVED** [review]
Maybe make the adjustments we talked about in the meeting today but other than that: Looks good

**Review by Victor-M-Giraldo — APPROVED** [review]

**Pull request merged**
