### PR TITLE
poster: add another diagram and more detailing

### PR DESCRIPTION
**Pull request by dyc3**
- **add details to poster**
- **put main items in a grid**
- **everything fits on page**
- **optimize svgs**
- **formatting**
- **update bullets**
- **add horizontal vs vertical scaling diagrams**

### CODE REVIEW

**Comment by Victor-M-Giraldo** [comment]
This looks weird when I compile it on my computer. Is it like this for you?
chrome_oRqmPqt6Ep

**Comment by dyc3** [comment]
That is not how it renders on my machine. Might be an upstream bug so id like to report it. Did you render in WSL or the windows version of typst?

**Comment by Victor-M-Giraldo** [comment]
> That is not how it renders on my machine. Might be an upstream bug so id like to report it. Did you render in WSL or the windows version of typst?

WSL.

**Comment by dyc3** [comment]
Do you get the same thing if you try to render it with the windows version?

**Comment by Victor-M-Giraldo** [comment]
Yes.

**Comment by dyc3** [comment]
I think it has something to do with the calls to `h(1fr)`. Not sure why it would differ by platform though.

**Comment by Victor-M-Giraldo** [comment]
Do you mind just posting a picture of the poster here then?

**Comment by dyc3** [comment]
image

**Review by Victor-M-Giraldo — APPROVED** [review]

**Pull request merged**
