### PR TITLE
made changes professor requested to monolith selection figure

### PR DESCRIPTION
**Pull request by Victor-M-Giraldo**
Changed orientation of figure and specified relationship between MonolithSelection and MinRoomsSelector

### CODE REVIEW

**Comment by Victor-M-Giraldo** [comment]
Just making the change the professor suggested to the figure today.

`make figures` has stopped working. I was trying to figure out why and didn't find anything online.

I got the following error: `ERROR: the following commands could not be found: parallel java dot`

I think I just need to reinstall those through the terminal, not sure.

**Comment by dyc3** [comment]
yes, reinstall those. Read the script, the error comes from there

**Comment by Victor-M-Giraldo** [comment]
Got it working, it re-rendered all of them though. Not sure why.

**Comment by dyc3** [comment]
yeah don't commit all the figures, only the ones you changed

**Review by dyc3 — APPROVED** [review]

**Pull request merged**
