### PR TITLE
Add draft to poster to doc

### LINKED ISSUE #344: Make poster with Typst and add it to repo

### PR DESCRIPTION
**Pull request by Victor-M-Giraldo**
- Closes #344

### CODE REVIEW

**Comment by Victor-M-Giraldo** [comment]
I took screenshots of the logos at the bottom and converted them to SVGS, but the quality was pretty bad. I'm hoping Darian will get back to me soon. I'm going to send him a follow up email.

This also isn't the same exact layout.

Do you know what relevant part of the docs I can read to see how I can only apply column layout to a certain part? For example, if we wanted to have the figures not be part of the two columns I'm not sure how to do that.

**Comment by dyc3** [comment]
The columns example here seems to do that: https://typst.app/docs/reference/layout/columns/ just by wrapping the content instead of using a `show` rule. IIRC `show` applies to the entire context that it's included in, not just what's below it.

**Comment by Victor-M-Giraldo** [comment]
I think this is as close as I can get it until Darian gets back to us about the images at the bottom of the template poster.

**Review by dyc3 — APPROVED** [review]
Good for draft

**Pull request merged**
